### ISSUE TITLE
Update "Content types to restrict"

### ISSUE THREAD

**Issue by tannerm** [skillfulplugins/rcp-view-limit#1]
This looks a bit messy to me, can we change to checkboxes? 
![image 2019-03-06 at 4 23 11 pm](https://user-images.githubusercontent.com/1952618/53923180-2ed59a00-402c-11e9-8c12-f62b0a296de9.png)

**Comment by landbryo** [comment]
@tannerm That is probably a better approach. I'll get that switched over.
